global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uptime-kuma'
    scrape_interval: 30s
    static_configs:
      - targets: ['uptime-kuma:3001']
    basic_auth:
      username: mykuma
      password: extremelysecret
  - job_name: 'postfix'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:9154']
  - job_name: 'mailcow'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:9099']