version: '3.8'

networks:
  monitor-net:
    driver: bridge
services:
    grafana:
        image: grafana/grafana:10.3.0
        container_name: grafana
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        restart: unless-stopped
        expose:
            - 3000
        networks:
            - monitor-net
        environment:
            GF_ANALYTICS_REPORTING_ENABLED: false
            GF_SECURITY_ADMIN_USER: ${ADMIN_USER}
            GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ## Good
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.36.2
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./prometheus/data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        restart: unless-stopped
        networks:
            - monitor-net
        ## Allow prometheus access to our other stacks
        extra_hosts:
            - "host.docker.internal:host-gateway"

    uptime-kuma:
        image: louislam/uptime-kuma:1
        restart: unless-stopped
        expose:
            - 3001
        networks:
            - monitor-net
        volumes:
            - ./uptime-kuma/data:/app/data

