global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 15s
    - static_configs:
        - targets: ['node-exporter:9100']

  - job_name: 'uptime-kuma'
    scrape_interval: 30s
    - static_configs:
        - targets: ['uptime-kuma:3001']
    basic_auth:
      username: mykuma
      password: extremelysecret
